// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfrhingfdteydwuvuttg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmcmhpbmdmZHRleWR3dXZ1dHRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAzNTY3NDIsImV4cCI6MjA3NTkzMjc0Mn0.gMz0JEyL-4xTf9tLQfSnitEe74-IgWfN02_jP_1A2u0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});